# Generated by Django 3.2.21 on 2023-09-09 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sport', 'SPORT'), ('music', 'MUSIC'), ('culture', 'CULTURE'), ('books', 'BOOKS'), ('education', 'EDUCATION'), ('business', 'BUSINESS'), ('fitness', 'FITNESS'), ('food_drink', 'FOOD AND DRINK'), ('games', 'GAMES')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'type')},
            },
        ),
    ]
