# Generated by Django 3.2.21 on 2023-09-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sport', 'SPORT'), ('music', 'MUSIC'), ('culture', 'CULTURE'), ('books', 'BOOKS'), ('education', 'EDUCATION'), ('business', 'BUSINESS'), ('fitness', 'FITNESS'), ('food_drink', 'FOOD AND DRINK'), ('games', 'GAMES')], max_length=30)),
            ],
        ),
    ]
